rvm: '2.2.1'

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq postgresql-server-dev-9.4

before_script:
  - psql -c 'create database chitter_test;' -U postgres

script:
  - rake auto_migrate
  - bundle exec rspec spec
  - bundle exec cucumber

