rvm: '2.2.1'

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
script:
  - bundle exec rspec spec
  - bundle exec cucumber
  - rake auto_migrate

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq postgresql-server-dev-9.3

